DIR_Config   = ./lib/Config
DIR_DRIVER      = ./lib/Driver
DIR_Examples = ./examples
DIR_BIN      = ./bin

CC = aarch64-linux-gnu-gcc
CFLAGS = -Wall -Wextra -pthread -I./lib/Driver -I./lib/Config

Datafetcher.o:
	$(CC) $(CFLAGS) -c Datafetcher.c -o /dev/null

Signalprocessing2.o:
	$(CC) $(CFLAGS) -c Signalprocessing2.c -o /dev/null
